apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appname-pipelines-dev
resources:
  - ../appname-shared
  - pipeline.yaml
  - npm-build-test.yaml
  - sonarqube-cli-scan.yaml
  - s2i-buildconfig.yaml
  - s2i-build-task.yaml
  - pvc.yaml
  - rbac.yaml
