# OpenShift が実行する Node.js Binary Source-to-Image Build
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: appname-frontend
  labels:
    app.kubernetes.io/part-of: appname-cicd
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: appname-frontend-s2i
  labels:
    app.kubernetes.io/part-of: appname-cicd
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/nodejs-24:latest
      env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "8080"
        - name: NPM_CONFIG_REGISTRY
          value: http://nexus-repo-service.nexus.svc.cluster.local:8081/repository/npm-public/
  output:
    to:
      kind: ImageStreamTag
      name: appname-frontend:latest
