apiVersion: v1
kind: ConfigMap
metadata:
  name: appname-backend-config
  labels:
    app: appname-backend
    app.kubernetes.io/part-of: appname
data:
  SPRING_PROFILES_ACTIVE: "dev"
  JAVA_OPTS: "-Xms256m -Xmx512m"
