apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: appname-apps-dev

images:
  - name: appname-backend
    newName: image-registry.openshift-image-registry.svc:5000/appname-pipelines-dev/appname-backend
    newTag: latest
  - name: appname-frontend
    newName: image-registry.openshift-image-registry.svc:5000/appname-pipelines-dev/appname-frontend
    newTag: latest
